name: Build font

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
    tags:
      - "*"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ttfautohint
      - name: Build font
        run: make build
      - name: Check with FontBakery
        run: make test
        continue-on-error: true
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: heblock-fonts
          path: |
            fonts
            out
